services:
  bandwagon-dashboard:
    image: dhslegle/bandwagon-dashboard:latest
    container_name: bandwagon-dashboard
    restart: always
    ports:
      - '3000:3000'
    env_file:
      - /data/app/bandwagon-dashboard/.env